fn main() {
    // Embed a UAC manifest into razer-daemon.exe so Windows automatically
    // prompts for elevation when the binary is launched.  The daemon requires
    // Administrator privileges to open Razer HID feature reports (mi_02).
    //
    // `/SUBSYSTEM:WINDOWS` suppresses the console window so the daemon runs
    // invisibly in the background (like a service).  The TCP IPC still works
    // exactly the same — GUI/CLI connect as before.
    //
    // `rustc-link-arg-bin=NAME=FLAG` applies the linker flag only to the
    // named binary — no extra crate dependencies required.
    if std::env::var("CARGO_CFG_WINDOWS").is_ok() {
        println!(
            "cargo:rustc-link-arg-bin=razer-daemon=/MANIFESTUAC:level='requireAdministrator'"
        );
        // /SUBSYSTEM:WINDOWS hides the console window (daemon runs invisibly in background).
        // /ENTRY:mainCRTStartup tells the MSVC CRT to call main() instead of WinMain().
        println!("cargo:rustc-link-arg-bin=razer-daemon=/SUBSYSTEM:WINDOWS");
        println!("cargo:rustc-link-arg-bin=razer-daemon=/ENTRY:mainCRTStartup");
    }

    // Embed the app icon into razer-gui.exe.
    // The ICO is pre-generated by `uv run scripts/gen_icon.py`.
    // We locate rc.exe from the Windows SDK (available in the MSVC build env)
    // and compile data/resources.rc → OUT_DIR/gui.res, then link it in.
    if std::env::var("CARGO_CFG_WINDOWS").is_ok() {
        embed_gui_icon();
    }

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=data/razer.ico");
    println!("cargo:rerun-if-changed=data/resources.rc");
}

fn find_rc_exe() -> Option<std::path::PathBuf> {
    use std::path::PathBuf;
    use std::process::Command;

    // 1. rc.exe already on PATH (VS developer shell or vcvarsall)
    if Command::new("rc.exe").arg("/?").output().is_ok() {
        return Some(PathBuf::from("rc.exe"));
    }

    // 2. Env-vars set by vcvarsall / VS Dev Prompt
    if let (Ok(bin), Ok(ver)) = (
        std::env::var("WindowsSdkBinPath"),
        std::env::var("WindowsSDKVersion"),
    ) {
        let p = PathBuf::from(bin)
            .join(ver.trim_end_matches('\\'))
            .join("x64")
            .join("rc.exe");
        if p.exists() {
            return Some(p);
        }
    }

    // 3. Scan the standard Windows Kits installation directory.
    for root in &[
        r"C:\Program Files (x86)\Windows Kits\10\bin",
        r"C:\Program Files\Windows Kits\10\bin",
    ] {
        if let Ok(entries) = std::fs::read_dir(root) {
            // Pick the highest SDK version directory (names like "10.0.22621.0")
            let mut versions: Vec<_> = entries
                .flatten()
                .filter(|e| e.path().is_dir())
                .collect();
            versions.sort_by_key(|e| e.file_name());
            for entry in versions.into_iter().rev() {
                let rc = entry.path().join("x64").join("rc.exe");
                if rc.exists() {
                    return Some(rc);
                }
            }
        }
    }

    None
}

fn embed_gui_icon() {
    use std::path::PathBuf;

    let root = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let out  = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let rc_src = root.join("data").join("resources.rc");
    let res_out = out.join("gui.res");

    let Some(rc_exe) = find_rc_exe() else {
        eprintln!("build: rc.exe not found — icon will not be embedded");
        return;
    };

    let status = std::process::Command::new(&rc_exe)
        .arg(format!("/fo{}", res_out.display()))
        .arg(&rc_src)
        .current_dir(root.join("data"))   // so rc.exe finds razer.ico next to the .rc
        .status();

    match status {
        Ok(s) if s.success() => {
            println!("cargo:rustc-link-arg-bin=razer-gui={}", res_out.display());
        }
        other => eprintln!("build: rc.exe failed ({other:?}), icon will not be embedded"),
    }
}
